version: 0.2

phases:
  install:
    runtime-versions:
        python: 3.10
     commands:
      - pip3 --version
      - pip3 install --upgrade pip
      - pip3 install virtualenv
      - virtualenv venv
      - . venv/bin/activate
   build:
    commands:
      - pwd && ls
        #- zappa status $STAGE

      - echo Build started on `date`
