version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
        #commands:
        #- pip install --upgrade pip
        #- pip install virtualenv
  pre_build:
    commands:
      - pip install --upgrade pip
      - pip install virtualenv
      - python -m venv myenv
      - . myenv/bin/activate
      - pip install -r requirements.txt
      - mkdir -p $HOME/cache
      - cp -r -l myenv $HOME/cache/
      - cp -r -l $HOME/.pyenv $HOME/cache/
  build:
    commands:
      # Your build commands here
  post_build:
    commands:
      # Your post-build commands here

cache:
  paths:
    - '/root/.cache/pip'
    - '$HOME/cache/myenv'
    - '$HOME/cache/.pyenv'
