version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install --upgrade pip
      - pip install virtualenv
  pre_build:
    commands:
      - virtualenv venv
      - source venv/bin/activate
      - pip install -r requirements.txt -t $CODEBUILD_SRC_DIR/cache
  build:
    commands:
      # Your build commands here
  post_build:
    commands:
      # Your post-build commands here

cache:
  paths:
    - '/root/.cache/pip'
    - 'cache/**/*'
